version: "3.7"

volumes:
  pg: {}

services:
  postgres:
    image: postgres:13.4
    volumes:
      - ./etc/postgres/autoapply:/docker-entrypoint-initdb.d:z
      - pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    restart: on-failure
